"""activities engine

Revision ID: 775a830b8934
Revises: a354e60bb823
Create Date: 2026-03-04 15:17:36.620179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775a830b8934'
down_revision: Union[str, Sequence[str], None] = 'a354e60bb823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_code'), 'activities', ['code'], unique=False)
    op.create_index(op.f('ix_activities_subcategory_id'), 'activities', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_activities_unit_id'), 'activities', ['unit_id'], unique=False)
    op.create_table('service_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'activity_id', name='uq_service_activity')
    )
    op.create_index(op.f('ix_service_activities_activity_id'), 'service_activities', ['activity_id'], unique=False)
    op.create_index('ix_service_activities_service_activity', 'service_activities', ['service_id', 'activity_id'], unique=False)
    op.create_index(op.f('ix_service_activities_service_id'), 'service_activities', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_activities_service_id'), table_name='service_activities')
    op.drop_index('ix_service_activities_service_activity', table_name='service_activities')
    op.drop_index(op.f('ix_service_activities_activity_id'), table_name='service_activities')
    op.drop_table('service_activities')
    op.drop_index(op.f('ix_activities_unit_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_subcategory_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_code'), table_name='activities')
    op.drop_table('activities')
    op.drop_table('units')
    # ### end Alembic commands ###
