"""catalog add slug fields

Revision ID: dc1d51e2647d
Revises: 775a830b8934
Create Date: 2026-03-04 16:08:48.892543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1d51e2647d'
down_revision: Union[str, Sequence[str], None] = '775a830b8934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_constraint(op.f('categories_domain_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.add_column('domains', sa.Column('slug', sa.String(length=200), nullable=False))
    op.alter_column('domains', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_domains_slug'), 'domains', ['slug'], unique=True)
    op.add_column('services', sa.Column('slug', sa.String(length=200), nullable=False))
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.drop_constraint(op.f('services_subcategory_id_fkey'), 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.add_column('subcategories', sa.Column('slug', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_subcategories_slug'), 'subcategories', ['slug'], unique=True)
    op.drop_constraint(op.f('subcategories_category_id_fkey'), 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('subcategories_category_id_fkey'), 'subcategories', 'categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_subcategories_slug'), table_name='subcategories')
    op.drop_column('subcategories', 'slug')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key(op.f('services_subcategory_id_fkey'), 'services', 'subcategories', ['subcategory_id'], ['id'])
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.alter_column('services', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('services', 'slug')
    op.drop_index(op.f('ix_domains_slug'), table_name='domains')
    op.alter_column('domains', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('domains', 'slug')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_domain_id_fkey'), 'categories', 'domains', ['domain_id'], ['id'])
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
